# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'CHANGEME'
      WEBPASSWORD: 'CHANGEME'
      FTLCONF_REPLY_ADDR4: 192.168.8.4
      PIHOLE_DNS_: 127.0.0.1#5053
      DNSSEC: "true"
      REV_SERVER: "true"
      REV_SERVER_TARGET: 192.168.8.1
      REV_SERVER_DOMAIN: localdomain
      REV_SERVER_CIDR: 192.168.8.0/24
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      macvlan:
        ipv4_address: 192.168.8.4

  proxy-dns:
    build:
      context: .
      dockerfile: Dockerfile.cloudflared
    command: proxy-dns --port=5053 --max-upstream-conns 50
    environment:
      TUNNEL_DNS_UPSTREAM: CHANGEME
    restart: always
    network_mode: "container:pihole"

volumes:
  pihole:
  dnsmasq:

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.8.0/24
