# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
#
# Example .env:
# TZ=CHANGEME
# MACVLAN_IPV4_ADDRESS=CHANGEME
# MACVLAN_IPV4_SUBNET=CHANGEME
# FTLCONF_dns_revServers=CHANGEME
# FTLCONF_webserver_api_password=CHANGEME

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ:
      FTLCONF_webserver_api_password:
      FTLCONF_dns_upstreams: 127.0.0.1#5053
      FTLCONF_dns_dnssec: "true"
      FTLCONF_dns_revServers:
    volumes:
      - "pihole:/etc/pihole/"
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: ${MACVLAN_IPV4_ADDRESS}

  nextdns:
    image: zydou/nextdns:latest
    environment:
      NEXTDNS_ID: a1b532
      NEXTDNS_ARGUMENTS: "-listen :5053 -report-client-info"
    restart: always
    network_mode: "container:pihole"

volumes:
  pihole:
  dnsmasq:

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${MACVLAN_IPV4_SUBNET}
